/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    Avatar: typeof import('./src/components/Navigation/Avatar.vue')['default']
    DialogModal: typeof import('./src/components/DialogModal/index.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld/index.vue')['default']
    IconFont: typeof import('./src/components/IconFont/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    LayoutArea: typeof import('./src/components/Layout/LayoutArea.vue')['default']
    LayoutSection: typeof import('./src/components/Layout/LayoutSection.vue')['default']
    LayoutView: typeof import('./src/components/Layout/LayoutView.vue')['default']
    NavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
    Octocat: typeof import('./src/components/Footer/octocat.vue')['default']
    OptionsMenu: typeof import('./src/components/OptionsMenu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCorporation: typeof import('./src/components/SearchSelect/SearchCorporation.vue')['default']
    SearchSelect: typeof import('./src/components/SearchSelect/index.vue')['default']
    SideAction: typeof import('./src/components/Navigation/Side/SideAction.vue')['default']
    SideGoBack: typeof import('./src/components/Navigation/Side/SideGoBack.vue')['default']
    SideLogo: typeof import('./src/components/Navigation/Side/SideLogo.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
